### PR TITLE
Adding a new product - battle axe

### PR DESCRIPTION
**Pull request by bausano**
Also there's a fix to the war hammer description

### CODE REVIEW

**Comment by bausano** [comment]
Also, if I wanted to deploy it to Vercel myself, is there some sort of settings necessary to bundle with the app? I've seen some env vars regarding email, perhaps there are others? Would it be possible to get the values emailed please?

**Comment by claryaldringen** [comment]
> Also, if I wanted to deploy it to Vercel myself, is there some sort of settings necessary to bundle with the app? I've seen some env vars regarding email, perhaps there are others? Would it be possible to get the values emailed please?

**Comment by claryaldringen** [comment]
> Also, if I wanted to deploy it to Vercel myself, is there some sort of settings necessary to bundle with the app? I've seen some env vars regarding email, perhaps there are others? Would it be possible to get the values emailed please?

I've enabled deploy on Vercel so every

**Comment by claryaldringen** [comment]
> Also, if I wanted to deploy it to Vercel myself, is there some sort of settings necessary to bundle with the app? I've seen some env vars regarding email, perhaps there are others? Would it be possible to get the values emailed please?

Deploying on the Vercel should be enabled now. You should see the link on current PR version in Vercel's bot comment. If everything will be ok, feel free to merge the PR 🙂

**Comment by bausano** [comment]
I pushed some more changes and unfortunately I don't have a green pass from Vercel, it applied only to the specific commit you approved I suppose

**Pull request merged**
